name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

#     - name: Set up Go 1.13
#       uses: actions/setup-go@v1
#       with:
#         go-version: 1.13
#       id: go

#     - name: Check out code into the Go module directory
#       uses: actions/checkout@v1
    
#     - name: Setup timezone
#       uses: zcong1993/setup-timezone@master
#       with:
#         timezone: Asia/Taipei

    - name: set git config
      run:  git config --global user.email "sappy5678@gmail.com" && git config --global user.name "sappy5678" && git config --global core.autocrlf false
    
    - uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.112.7'
        extended: true
        
    
        
    
    - name: mv files to post folder
      run: echo $(pwd) && echo $(ls) && mkdir posts && mv $(ls | grep -v 'posts')  posts && echo $(ls posts)

    - name: clone blog
      run: git clone --recursive https://sappy5678:${{ secrets.hugo_blog_push }}@github.com/sappy5678/hugo_blog.git
      
    - name: pull notes
      run: rm -rf hugo_blog/content/posts && rm -rf hugo_blog/docs && mv posts hugo_blog/content/posts && echo $(ls hugo_blog/content/posts)

#     - name: pull notes
#       working-directory: hugo_blog/content/posts
#       run: echo $(ls) && git pull https://sappy5678:${{ secrets.hugo_blog_push }}@github.com/sappy5678/notes.git master



  
      
    - name: build blog
      working-directory: hugo_blog
      run: hugo --minify

    - name: debug
      working-directory: hugo_blog
      run: echo $(shasum -a 256 docs/css/*)
    
    - name: setting CNAME
      run: echo "blog.sappy.tw" >>  hugo_blog/docs/CNAME
    

    
    # - name: format crlf to lf
    #   working-directory: hugo_blog
    #   run: find . -type f -exec sed -i "s/^M$//" {} \; 

    - name: push
      working-directory: hugo_blog
      run: git add . && git commit -m $GITHUB_SHA && git push 

#     - name: build blog
#       run: hugo -D
      
#     - name: Get dependencies
#       run: |
#         go get -v -t -d ./...
#         if [ -f Gopkg.toml ]; then
#             curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
#             dep ensure
#         fi

#     - name: Build
#       run: go build -v .
